# This cron job will run every 23h 59min to check if zig 
# master has breaking changes
name: zig changes watch

on:
  schedule:
    # Run every night at 04:00
    - cron: "00 04 * * 0-6"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download zig
        run: wget https://ziglang.org/builds/zig-linux-x86_64-0.13.0-dev.351+64ef45eb0.tar.xz

      - name: Install zig
        run: tar -xf zig-linux-x86_64-0.13.0-dev.351+64ef45eb0.tar.xz && mv zig-linux-x86_64-0.13.0-dev.351+64ef45eb0/* ./

      # build examples to test for compile issues
      - name: Build examples 
        run: ./zig build
